name: Zenith

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Set Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build production bundle
              run: pnpm build --config docusaurus-zenith.config.ts

            - name: Zip Build
              run: zip -r build.zip *
              working-directory: build

            - uses: actions/upload-artifact@v4
              with:
                  path: build/build.zip
                  if-no-files-found: error

    deploy:
        if: ${{ github.event_name == 'push' }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/download-artifact@v5
            - shell: bash
              env:
                  DEPLOY_URL: ${{ vars.DEPLOY_URL }}
                  DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
              run: 'curl -X POST $DEPLOY_URL -H "Content-Type:application/octet-stream" --data-binary "@build.zip" -H "X-Gitlab-Token: $DEPLOY_TOKEN"'
